### ISSUE TITLE
Migration to 14.0

### ISSUE THREAD

**Issue by sergiocorato** [efatto/e-account#2]
- [x] ~account_analytic_line_usability~ not used
- [x] account_balance_line_progressive #6 
- [x] ~account_bank~ deprecated
- [x] ~account_closing_data~ not used
- [x] ~account_fiscal_year_closing_fix_reconcile~ recreated PR https://github.com/OCA/account-closing/pull/247
- [x] ~account_fiscal_year_closing_reporting~ deprecated in favour of https://github.com/OCA/account-closing/pull/134#issuecomment-685795140
- [x] account_invoice_discount_update #9
- [x] account_invoice_dueamount #7
- [x] account_invoice_filter_country #10
- [x] account_invoice_line_usability #11
- [x] ~account_invoice_refund_update_sale~ no more needed
- [x] account_invoice_tree_payment #12 
- [x] ~account_invoice_user_editable~ no more needed
- [x] account_invoice_weight (from 8.0) #32 
- [x] ~account_move_line_usability~ i think this is no more needed, migrate in case of complaints
- [x] account_sequence_accountant #8 
- [x] ~account_vat_statement_report~ not used
- [x] ~base_vat_sanitized_unique~ no more needed see https://github.com/OCA/partner-contact/pull/862
- [x] ~l10n_it_fatturapa_in_dueamount~ no more needed
- [ ] l10n_it_fatturapa_out_pa
- [x] ~l10n_it_fatturapa_out_sale~ not used
- [x] l10n_it_intrastat_code_sale #24 
- [x] l10n_it_ricevute_bancarie_accrual
- [x] l10n_it_ricevute_bancarie_unsettlement
- [x] mail_no_autofollow #20 
- [x] mail_no_follower_notification #21
- [ ] mail_thread_assign_task_project
- [ ] mis_builder_analytic_query
- [x] mis_builder_cash_flow_inheritable #29 
- [x] mis_builder_cash_flow_purchase #30 
- [ ] mis_builder_expand_partner
- [x] mis_builder_query_drilldown #28 
- [x] mis_builder_query_drilldown_view
- [x] product_margin_exclude #25 
- [x] product_pricelist_rounding
- [x] ~purchase_order_line_dueamount~ replaced by #30 
- [x] res_partner_payment_term_m2o #4 
- [x] ~res_partner_phone_email_required~ not used
- [x] ~res_partner_vat_fiscalcode_required~ not used
- [x] res_partner_view_account #15
- [ ] sale_crm_view_usability
- [x] sale_date_order_visibility #13 
- [x] sale_order_analytic_all #5 
- [x] sale_order_date_order_visibility #17
- [x] sale_order_line_date_order #16
- [x] ~sale_order_line_dueamount~ replaced by #31 
- [x] sale_order_line_menu_usability #18
- [x] sale_order_line_usability #45 
- [ ] sale_order_margin_cancelled
- [x] sale_order_margin_state #27 
- [ ] sale_order_revision_analytic
- [x] sale_order_revision_preserve #23 
- [ ] sale_order_shipping_childs_limit
- [x] sale_order_tree_client_ref #22 
- [x] sale_order_view_usability #26 
- [ ] sale_project_visibility
- [x] sale_view_client_order_ref #14
